name: 'Platform.sh CLI'
description: 'Run platform.sh CLI commands'
branding:
  icon: 'terminal'
  color: 'gray-dark'
inputs:
  project:
    description: 'Platform.sh project ID'
    required: true
  command:
    description: 'Command to run'
    required: false
    default: 'list'
outputs:
  result:
    description: 'Command result'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project }}
    - ${{ inputs.command }}
