name: CI

on:
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Get version
        uses: ./
        id: version
        with:
          command: --version
      - name: Check version
        env:
          current: ${{ steps.version.outputs.result }}
          expected: "Platform.sh CLI 3.60.4"
        run: |
          if [ "$current" != "$expected" ]
          then
            exit 1
          fi

