name: PR title

on:
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        uses: ./
        id: version
        with:
          token: abc
          project: def
          command: --version
      - name: Check version
        run: |
          if [ "${{ steps.version.outputs.result }}" -ne "Platform.sh CLI 3.60.4" ]
          then
            exit 0
          fi

